# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: '$(System.DefaultWorkingDirectory)/ejemploWebApi'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Ejecuta comando build con argumentos --configuration $(BuildConfiguration) --output $(System.DefaultWorkingDirectory)'
  inputs:
    command: 'publish'
    workingDirectory: '$(System.DefaultWorkingDirectory)/ejemploWebApi'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(System.DefaultWorkingDirectory)'
    zipAfterPublish: True

- task: CopyFiles@2
  displayName: 'Copia todos los Archivos con excepcion de la carpeta .Git, a la ruta: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
     **/*
     !.git/**/*
    targetFolder: $(Build.ArtifactStagingDirectory)   

- task: PublishBuildArtifacts@1
  displayName: 'Construye Artefacto MiCompilado. Publica Sitio en Ruta: $(Build.ArtifactStagingDirectory)'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MiCompilado